### ISSUE TITLE
Documentation on how to use settings_gui?

### ISSUE THREAD

**Issue by dhyanKaro** [SamuLumio/object-settings#1]
Guide me!

**Comment by SamuLumio** [comment]
Yeah that would work, just two things: you don't need to call `enable_ttk()`, that gets done automatically (should have probably made it a private method). Second, the `save_button` parameter is supposed to be True/False for if the save button is shown, but I guess this still technically works because python interperets a non-empty string as True. (If you want to customize strings in the gui like the save button text, you can call `settings_gui.config.strings()` the same way you call `settings.config()`)

I agree some documentation on that would be good. Imma try expanding the readme a little bit.

**Comment by SamuLumio** [comment]
I've updated the readme, what do you think?

**Comment by dhyanKaro** [comment]
> I've updated the readme, what do you think?

I like it.

**Comment by SamuLumio** [comment]
👍
